---
- name: Set hostname
  hostname:
    name: "{{ os_hostname }}"

- name: Perform apt dist upgrade
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Add packages
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages }}"
